language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install: "pip install -r requirements-dev.txt --use-mirrors"
script: >
  if python -V 2>&1 |grep -q '^Python 3'; then
    nosetests --version && nosetests
  else
    pip install pycurl
    make test
  fi
